#!/usr/bin/env bash

##cosmetic functions and Variables
##Colors
RED='\033[0;31m'
YELLOW='\033[0;33m'
GREEN='\033[0;32m'
NC='\033[0m'
BLUE='\033[0;34m'

##Break function for readabillity
BR()
{
  echo "  "
}

##DoubleBreak function for readabillity
DBR()
{
  echo " "
  echo " "
}

printf "${GREEN}Enter the begin date in format dd/mm/yyyy ${NC}\n"
read beginDate
printf "${GREEN}Enter the amount of days ${NC}\n"
read amount
date -j -v +"$amount"d -f "%d/%m/%Y" "$beginDate"
