#!/usr/bin/env bash
plistConfig="/Users/UCB/Documents/UCB/Scriptz/Tests/PLT001-DEV.plist"
endPointsArg="JELIZE"
environmentArg=ACC

cat $plistConfig
echo  -----------

urlCalculator()
{

  ## review endpoints
  case $environmentArg in
    PRD )
    apiUrl="https://"$endPointsArg"-api-mtls.my.ucb.com"
    tokenUrl="https://"$endPointsArg"-token-mtls.my.ucb.com"
    apiSignalrOrigin="https://"$endPointsArg"-televisits.my.ucb.be"
    apiSignalrUrl="https://apis.ucb-apps.be/v1/btpa-"$endPointsArg"-api"
    notificationHubNamespace="ucb-nhn-btpm"
    notificationHubName="ucb-anh-btpm-001"
    notificationHubKeyName="DefaultListenSharedAccessSignature"
    notificationHubKey="k23Kc0baqrUrpun9/1/suVLHMVWJiEtEFFnN06raF3Y="
      ;;
    ACC )
    apiUrl="https://"$endPointsArg"-acc-api-mtls.my.ucb-acc.com"
    tokenUrl="https://"$endPointsArg"-acc-token-mtls.my.ucb-acc.com"
    apiSignalrOrigin="https://"$endPointsArg"-acc-televisits.my.ucb-acc.be"
    apiSignalrUrl="https://apis.ucb-apps.be/v1/acc-btpa-"$endPointsArg"-api"
    notificationHubNamespace="ucb-nhn-btpm"
    notificationHubName="ucb-anh-btpm-001"
    notificationHubKeyName="DefaultListenSharedAccessSignature"
    notificationHubKey="k23Kc0baqrUrpun9/1/suVLHMVWJiEtEFFnN06raF3Y="
      ;;
    DEV )
    apiUrl="https://"$endPointsArg"-dev-api-mtls.my.ucb-dev.com"
    tokenUrl="https://"$endPointsArg"-dev-token-mtls.my.ucb-dev.com"
    apiSignalrOrigin="https://"$endPointsArg"-dev-televisits.my.ucb-dev.be"
    apiSignalrUrl="https://apis.ucb-apps.be/v1/dev-btpa-"$endPointsArg"-api"
    notificationHubNamespace="ucb-nhn-btpm"
    notificationHubName="ucb-anh-btpm-801"
    notificationHubKeyName="DefaultListenSharedAccessSignature"
    notificationHubKey="Rmp8z+65mKw+lpdkITudYNJctFDVPGAScg6SX2ggd+U="
      ;;
  esac
}


editConfigPlist()
{
#plistConfig="$payloadFolder/$payloadApp/Config.plist"
apiTokenUrlInConfig=$(grep -A1 '<key>apiTokenUrl</key>' $plistConfig | grep -v "<key>apiTokenUrl</key>")
apiUrlInConfig=$(grep -A1 '<key>apiUrl</key>' $plistConfig | grep -v "<key>apiUrl</key>")
apiSignalrOriginInConfig=$(grep -A1 '<key>apiSignalrOrigin</key>' $plistConfig | grep -v "<key>apiSignalrOrigin</key>")
apiSignalrUrlInConfig=$(grep -A1 '<key>apiSignalrUrl</key>' $plistConfig | grep -v "<key>apiSignalrUrl</key>")
notificationHubNamespaceInConfig=$(grep -A1 '<key>notificationHubNamespace</key>' $plistConfig | grep -v "<key>notificationHubNamespace</key>")
notificationHubNameInConfig=$(grep -A1 '<key>notificationHubName</key>' $plistConfig | grep -v "<key>notificationHubName</key>")
notificationHubKeyNameInConfig=$(grep -A1 '<key>notificationHubKeyName</key>' $plistConfig | grep -v "<key>notificationHubKeyName</key>")
notificationHubKeyInConfig=$(grep -A1 '<key>notificationHubKey</key>' $plistConfig | grep -v "<key>notificationHubKey</key>")
echo replace apiTokenUrl
LC_ALL=C sed -i '' -e "s|$apiTokenUrlInConfig|  <string>$tokenUrl<\/string>|g" $plistConfig
echo replace apiUrl
LC_ALL=C sed -i '' -e "s|$apiUrlInConfig|  <string>$apiUrl<\/string>|g" $plistConfig
echo replace apiSignalrUrl
LC_ALL=C sed -i '' -e "s|$apisignalUrlInConfig|  <string>$apiSignalrUrl<\/string>|g" $plistConfig
echo replace apiSignalrOrigin
LC_ALL=C sed -i '' -e "s|$apiSignalrOriginInConfig|  <string>$apiSignalrOrigin<\/string>|g" $plistConfig
echo replace notificationHubNamespace
LC_ALL=C sed -i '' -e "s|$notificationHubNamespaceInConfig|  <string>$notificationHubNamespace<\/string>|g" $plistConfig
echo replace notificationHubName
LC_ALL=C sed -i '' -e "s|$notificationHubNameInConfig|  <string>$notificationHubName<\/string>|g" $plistConfig
echo replace notificationHubKeyName
LC_ALL=C sed -i '' -e "s|$notificationHubKeyNameInConfig|  <string>$notificationHubKeyName<\/string>|g" $plistConfig
echo replace notificationHubKey
LC_ALL=C sed -i '' -e "s|$notificationHubKeyInConfig|  <string>$notificationHubKey<\/string>|g" $plistConfig

}

urlCalculator
editConfigPlist



# editConfigPlist

cat $plistConfig
