#!/usr/bin/env bash

##cosmetic functions and Variables
##Colors
RED='\033[0;31m'
YELLOW='\033[0;33m'
GREEN='\033[0;32m'
NC='\033[0m'
BLUE='\033[0;34m'

##Break function for readabillity
BR()
{
  echo "  "
}

##DoubleBreak function for readabillity
DBR()
{
  echo " "
  echo " "
}

repoFolder="/Volumes/Macintosh HD-1/Users/Shared/myUCB4me_AppRepo"
ipaVersionArg=1.5.0_19298.2
#ipaVersionArg=1.4.0_19199.4
#ipaArg="/Volumes/Macintosh HD-1/Users/Shared/myUCB4me_AppRepo/com.ucb.apps.myucb4me.dev_1.5.0_19298.2.ipa"
deviceUDIDArg=635ed719e26e136be44c84dbf8f4422849cc428c
provisioningProfilePath="/Users/UCB/Documents/UCB/Scriptz/HPMC_Resign/_SharedResources/ProvisioningProfile/HPMC_HpMobileCenter.mobileprovision"
sharedResourcesPath="/Users/UCB/Documents/UCB/Scriptz/HPMC_Resign/_SharedResources"

UDIDPresence=$(strings "$sharedResourcesPath/ProvisioningProfile/HPMC_HpMobileCenter.mobileprovision" | grep -c $deviceUDIDArg)

echo $UDIDPresence
